# -*- coding: utf-8 -*-
"""Project Telco - Cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQhEz1vd5Qjq2VEnTcOr4oL5VoNXCNrC
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df_master = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco.csv']))

df = df_master.copy()

df.info()

df.describe()

#Step 1: Filtering customerID with character length 11-12 
#Part a: convert data type into string

df["customerID"] = df["customerID"].astype(str)
df.info()

#Part b: filtering character length of the column customerID which has 11-12 character length

long = df[(df["customerID"].str.len() == 11) | (df["customerID"].str.len() == 12)]

#Part c: Check the length of row which has 11-12 range of character, also check the row amount of other column. If it has same amount of row as customerID then it has filtered well
long.info()

#Step 2: Filtering data with value number only

number=long[long["customerID"].str.isnumeric()]
number.info()

#Step 3: Filtering "customerID" with the two first number is 45

first45 = number[number["customerID"].str[:2] == "45"]

#Langkah 4: Dropping duplicate ID and sorting it out
df_load = first45.drop_duplicates(subset="customerID")
df_load.info()

#Step 5: Checking how many the missing values are
df_load.isnull().sum()

#Step 6: Fixing missing value

df_load["tenure"].fillna("11", inplace = True) 
df_load["MonthlyCharges"].fillna(value=df['MonthlyCharges'].median(), inplace = True) 
df_load["TotalCharges"].fillna(value=df['TotalCharges'].median(), inplace = True)

df_load.isnull().sum()

df_load.groupby('Churn')['customerID'].nunique()

#Fill the N/A of column Churn with the least of the data, which is 'Churn'
df_load["Churn"].fillna("Yes", inplace = True)
df_load["Churn"] = df_load["Churn"].replace(['Churn'],'Yes')

df_load.groupby('gender')['customerID'].nunique()

#Step 7: Eliminate categories with similar meaning

df_load = df_load.replace(['Laki-Laki'],'Male')
df_load = df_load.replace(['Wanita'],'Female')
df_load["Dependents"] = df_load["Dependents"].replace(['Iya'],'Yes')

df_load.groupby('gender')['customerID'].nunique()

df.info()

#Step 8: Finding outlier by visualizing the data using boxplot

#Part a: Changing data type to int or float
df_load["tenure"] = df_load["tenure"].astype(float)
df_load["tenure"].dtypes

#Part b: Starting to visualize the numerical data

df_box = pd.DataFrame(df_load, columns = ['tenure'])
df_box[['tenure']].boxplot()

#Checking description as consideration for the next step
df_load["tenure"].describe()

#Changing value of the outlier using IQR
Q1 = (df_load[['tenure']]).quantile(0.25)
Q3 = (df_load[['tenure']]).quantile(0.75)

IQR = Q3 - Q1
maximum  = Q3 + (1.5*IQR)
print('The maximum value of each variables: ')
print(maximum)
minimum = Q1 - (1.5*IQR)
print('\nThe maximum value of each variables: ')
print(minimum)

#Implementing constraints and replacing the values
more_than     = (df_load > maximum)
lower_than    = (df_load < minimum)
df_load       = df_load.mask(more_than, maximum, axis=1) 
df_load       = df_load.mask(lower_than, minimum, axis=1)

#Changing value of the outlier using IQR
Q1 = (df_load[['tenure','MonthlyCharges','TotalCharges']]).quantile(0.25)
Q3 = (df_load[['tenure','MonthlyCharges','TotalCharges']]).quantile(0.75)

IQR = Q3 - Q1
maximum  = Q3 + (1.5*IQR)
print('The maximum value of each variables: ')
print(maximum)
minimum = Q1 - (1.5*IQR)
print('\nThe maximum value of each variables: ')
print(minimum)

more_than     = (df_load > maximum)
lower_than    = (df_load < minimum)
df_load       = df_load.mask(more_than, maximum, axis=1) 
df_load       = df_load.mask(lower_than, minimum, axis=1)

df_box = pd.DataFrame(df_load, columns = ['tenure'])
df_box[['tenure']].boxplot()

df_box = pd.DataFrame(df_load, columns = ['MonthlyCharges'])
df_box[['MonthlyCharges']].boxplot()

plt.boxplot(df_load.TotalCharges)

#Final checking missing value

df_load.isnull().sum()

df_load.to_csv('dqlab_telco_clean.csv', encoding='utf-8', index=False)
files.download('dqlab_telco_clean.csv')